{% set name = "pyahocorasick" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88f79307c74ae6a84f8d88c2522a082f1d21c425762aba7f7e4d14dd431d2fb7

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ahocorasick

about:
  home: https://github.com/WojciechMula/pyahocorasick
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python module (C extension and plain python) implementing Aho-Corasick algorithm.
  description: |
    pyahocorasick is a fast and memory efficient library for exact or approximate multi-pattern string
    search meaning that you can find multiple key strings occurrences at once in some input text.
    The library provides an ahocorasick Python module that you can use as a plain dict-like Trie or
    convert a Trie to an automaton for efficient Aho-Corasick search.
  dev_url: https://github.com/WojciechMula/pyahocorasick
  doc_url: http://pyahocorasick.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jonashaag
    - peterk87
