{% set name = "pyahocorasick" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 817f302088400a1402bf2f8631fdb21cf5a2666888e0d6a7d5a3ad556212e9da

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ahocorasick

about:
  home: https://github.com/WojciechMula/pyahocorasick
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python module (C extension and plain python) implementing Aho-Corasick algorithm.
  description: |
    pyahocorasick is a fast and memory efficient library for exact or approximate multi-pattern string
    search meaning that you can find multiple key strings occurrences at once in some input text.
    The library provides an ahocorasick Python module that you can use as a plain dict-like Trie or
    convert a Trie to an automaton for efficient Aho-Corasick search.
  dev_url: https://github.com/WojciechMula/pyahocorasick
  doc_url: http://pyahocorasick.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jonashaag
    - peterk87
