{% set name = "pyahocorasick" %}
{% set version = "1.4.0" %}
{% set sha256sum = "f9431a20e47e893cadd29f367825e882dbc6fc324a3c24c41e3ff9648e5d04b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ahocorasick

about:
  home: https://github.com/WojciechMula/pyahocorasick
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python module (C extension and plain python) implementing Aho-Corasick algorithm.'
  description: |
      pyahocorasick is a fast and memory efficient library for exact or approximate multi-pattern string
      search meaning that you can find multiple key strings occurrences at once in some input text.
      The library provides an ahocorasick Python module that you can use as a plain dict-like Trie or
      convert a Trie to an automaton for efficient Aho-Corasick search.
  dev_url: https://github.com/WojciechMula/pyahocorasick
  doc_url: http://pyahocorasick.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - hellothisisMatt
    - peterk87
